language: ruby
rvm:
  - 2.2.4
  - 2.3.0
script: bundle exec rspec
cache: bundler
gemfile:
  - Gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails5beta.gemfile
