---
version: 2.1

commands:
  shared_steps:
    steps:
      - checkout

      - restore_cache:
          name: Restore bundle cache
          key: v1-challah-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle Install
          command: |
            gem uninstall bundler
            gem install bundler -v=2.1.2
            bundle config set path 'vendor/bundle'
            bundle install

      - save_cache:
          name: Store bundle cache
          key: v1-challah-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

default_job: &default_job
  working_directory: ~/repo
  steps:
    - shared_steps

    - run:
        name: "Rails DB Migrate"
        command: |
          bundle exec rails db:migrate

    - run:
        name: "Rubocop"
        command: bundle exec rubocop

    - run:
        name: "RSpec"
        command: |
          bundle exec rspec --profile 10 \
                          --format RspecJunitFormatter \
                          --out /tmp/test-results/rspec.xml \
                          --format progress \
                          spec/

    - store_test_results:
        path: /tmp/test-results

jobs:
  ruby_26:
    <<: *default_job
    docker:
      - image: circleci/ruby:2.6-stretch-node
        environment:
          RAILS_ENV: test
      - image: redis:6.0

  ruby_27:
    <<: *default_job
    docker:
      - image: circleci/ruby:2.7-stretch-node
        environment:
          RAILS_ENV: test
      - image: redis:6.0

  ruby_30:
    <<: *default_job
    docker:
      - image: cimg/ruby:3.0-node
        environment:
          RAILS_ENV: test
      - image: redis:6.0


workflows:
  version: 2
  rubies:
    jobs:
      - ruby_26
      - ruby_27
      - ruby_30

